.\" primzahl.1
.TH primzahl 1 "Feb. 2002" "M. Gräfe" "C und Linux"
.SH NAME
primzahl \- Primzahlen von 1 bis 100 berechnen.
.SH SYNTAX
primzahl
.SH BESCHREIBUNG
.fi
Das Programm \fBprimzahl\fR berechnet alle Primzahlen
zwischen 1 und 100. Es dient als Beispielprogramm für
das erste Kapitel des Buches "\fIC und Linux\fR".
.nf
.SH AUTOR
Martin Gräfe (AuM.Graefe@t-online.de)
